# Find all peoples
GET http://localhost:8080/api/person/v1
Content-Type: application/xml
Accept: application/x-yaml
###

# Find one person
GET http://localhost:8080/api/person/v1/4
Content-Type: application/json
Accept: application/x-yaml
###

# Create person
POST http://localhost:8080/api/person/v1
Content-Type: application/x-yaml
Accept: application/x-yaml

---
first_name: "João"
last_name: "Andrade"
address: "Av. Alphaville, Alphaville I, Salvador - Bahia - BR"
gender: "Male"
###

# Update person
PUT http://localhost:8080/api/person/v1
Content-Type: application/x-yaml
Accept: application/x-yaml

---
id: 10
first_name: "João II"
last_name: "Andrade"
address: "Av. Alphaville, Alphaville I, Salvador - Bahia - BR"
gender: "Male"
###

# Delete person

DELETE  http://localhost:8080/api/person/v1/5
Content-Type: application/json
###